name: noise_meter
description: A Flutter plugin for collecting noise from the phone's microphone.
version: 3.0.2
author: CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_meter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_streamer:
    git:
      url: git@github.com:truthuntold/flutter-plugins.git
      ref: master
      path: packages/audio_streamer/
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
